
    create table audit_logs (
        created_at timestamp(6),
        id bigint generated by default as identity,
        user_id uuid,
        ip_address varchar(45),
        action_type varchar(100) not null,
        details TEXT,
        primary key (id)
    );

    create table booking_rooms (
        room_id bigint not null,
        booking_id uuid not null,
        primary key (room_id, booking_id)
    );

    create table bookings (
        adults_count integer not null,
        base_amount numeric(12,2) not null,
        check_in_date date not null,
        check_out_date date not null,
        children_count integer,
        discount_amount numeric(12,2),
        grand_total numeric(12,2) not null,
        tax_amount numeric(12,2),
        category_id bigint not null,
        coupon_id bigint,
        created_at timestamp(6),
        updated_at timestamp(6),
        guest_id uuid not null,
        id uuid not null,
        booking_reference varchar(20) not null unique,
        booking_status varchar(30) not null,
        primary key (id)
    );

    create table coupons (
        discount_value numeric(10,2) not null,
        expiry_date date not null,
        is_active boolean,
        max_discount_value numeric(10,2),
        min_booking_value numeric(10,2),
        start_date date not null,
        usage_limit integer,
        used_count integer,
        id bigint generated by default as identity,
        discount_type varchar(20) not null,
        code varchar(30) not null unique,
        primary key (id)
    );

    create table guests (
        total_spend numeric(12,2),
        total_stays integer,
        state_code varchar(5) not null,
        gstin varchar(15),
        mobile varchar(15) not null,
        id uuid not null,
        id_proof_type varchar(30),
        city varchar(50),
        first_name varchar(50) not null,
        last_name varchar(50) not null,
        email varchar(100) not null,
        address TEXT,
        id_proof_url TEXT,
        primary key (id)
    );

    create table housekeeping_tasks (
        completed_at timestamp(6),
        created_at timestamp(6),
        id bigint generated by default as identity,
        room_id bigint not null,
        assigned_to uuid,
        task_status varchar(30) not null,
        notes TEXT,
        primary key (id)
    );

    create table invoices (
        base_tariff_total numeric(12,2) not null,
        cgst_amount numeric(12,2),
        discount_applied numeric(12,2),
        grand_total numeric(12,2) not null,
        gst_percentage numeric(5,2) not null,
        igst_amount numeric(12,2),
        invoice_date date not null,
        sgst_amount numeric(12,2),
        place_of_supply varchar(5) not null,
        created_at timestamp(6),
        sac_code varchar(10) not null,
        gstin_resort varchar(15) not null,
        booking_id uuid not null,
        id uuid not null,
        invoice_number varchar(30) not null unique,
        primary key (id)
    );

    create table payments (
        amount numeric(12,2) not null,
        transaction_time timestamp(6),
        booking_id uuid not null,
        id uuid not null,
        payment_method varchar(30) not null,
        payment_status varchar(30) not null,
        razorpay_order_id varchar(100),
        razorpay_payment_id varchar(100),
        razorpay_signature varchar(255),
        primary key (id)
    );

    create table refresh_tokens (
        expiry_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        user_id uuid unique,
        token varchar(255) not null unique,
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(50) not null unique,
        description varchar(255),
        primary key (id)
    );

    create table room_categories (
        base_price numeric(10,2) not null,
        capacity integer not null,
        id bigint generated by default as identity,
        name varchar(50) not null unique,
        description TEXT,
        primary key (id)
    );

    create table room_category_amenities (
        category_id bigint not null,
        amenity varchar(255)
    );

    create table room_category_images (
        category_id bigint not null,
        image_url varchar(255)
    );

    create table room_category_inventory (
        blocked_count integer not null,
        booked_count integer not null,
        inventory_date date not null,
        total_inventory integer not null,
        category_id bigint not null,
        id bigint generated by default as identity,
        version bigint,
        primary key (id),
        unique (category_id, inventory_date)
    );

    create table rooms (
        floor integer not null,
        category_id bigint not null,
        id bigint generated by default as identity,
        room_number varchar(10) not null unique,
        status varchar(30) not null,
        primary key (id)
    );

    create table user_roles (
        role_id bigint not null,
        user_id uuid not null,
        primary key (role_id, user_id)
    );

    create table users (
        is_active boolean,
        mobile varchar(15) not null unique,
        id uuid not null,
        first_name varchar(50) not null,
        last_name varchar(50) not null,
        email varchar(100) not null unique,
        password_hash varchar(255) not null,
        primary key (id)
    );

    create index idx_booking_status 
       on bookings (booking_status);

    create index idx_booking_checkin 
       on bookings (check_in_date);

    create index idx_booking_checkout 
       on bookings (check_out_date);

    create index idx_hk_task_status 
       on housekeeping_tasks (task_status);

    create index idx_room_status 
       on rooms (status);

    alter table if exists audit_logs 
       add constraint FKjs4iimve3y0xssbtve5ysyef0 
       foreign key (user_id) 
       references users;

    alter table if exists booking_rooms 
       add constraint FKcjk0abrppkbsw5w03uq8tvgfc 
       foreign key (room_id) 
       references rooms;

    alter table if exists booking_rooms 
       add constraint FK71qgxnmri4s08xrlny5wptrej 
       foreign key (booking_id) 
       references bookings;

    alter table if exists bookings 
       add constraint FK4prx2x3cbjh4nu1jik8m408iu 
       foreign key (category_id) 
       references room_categories;

    alter table if exists bookings 
       add constraint FK101wogms8hhvwho3c7g9dha1r 
       foreign key (coupon_id) 
       references coupons;

    alter table if exists bookings 
       add constraint FKpvlyfwhomknrbmo2d20src5vi 
       foreign key (guest_id) 
       references guests;

    alter table if exists housekeeping_tasks 
       add constraint FKjrcbm8imq7c2i9y9cc4kqk99m 
       foreign key (assigned_to) 
       references users;

    alter table if exists housekeeping_tasks 
       add constraint FKbuj2qtxq2odlqhj9qivxxvawn 
       foreign key (room_id) 
       references rooms;

    alter table if exists invoices 
       add constraint FKb9bhb7xre5v64qvjeholh3qj0 
       foreign key (booking_id) 
       references bookings;

    alter table if exists payments 
       add constraint FKc52o2b1jkxttngufqp3t7jr3h 
       foreign key (booking_id) 
       references bookings;

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;

    alter table if exists room_category_amenities 
       add constraint FKipr9xp9mxxppahnolru60cnae 
       foreign key (category_id) 
       references room_categories;

    alter table if exists room_category_images 
       add constraint FK7fi0hwhsgq7atmprxlfdde6ij 
       foreign key (category_id) 
       references room_categories;

    alter table if exists room_category_inventory 
       add constraint FKld1ssqwjlxgh7yh55yumbldix 
       foreign key (category_id) 
       references room_categories;

    alter table if exists rooms 
       add constraint FKs3ya1bmk1lymqudi59qf826vl 
       foreign key (category_id) 
       references room_categories;

    alter table if exists user_roles 
       add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 
       foreign key (role_id) 
       references roles;

    alter table if exists user_roles 
       add constraint FKhfh9dx7w3ubf1co1vdev94g3f 
       foreign key (user_id) 
       references users;
