    create table restaurant_categories (
        id bigint generated by default as identity,
        name varchar(100) not null unique,
        description TEXT,
        is_active boolean default true,
        primary key (id)
    );

    create table restaurant_tables (
        id bigint generated by default as identity,
        category_id bigint not null,
        table_number varchar(20) not null unique,
        capacity integer not null,
        status varchar(30) not null default 'AVAILABLE',
        primary key (id),
        constraint FK_rest_table_cat foreign key (category_id) references restaurant_categories(id)
    );

    create table restaurant_reservations (
        id uuid not null,
        customer_id uuid not null,
        hotel_booking_id uuid,
        category_id bigint not null,
        table_id bigint not null,
        guest_count integer not null,
        reservation_date date not null,
        reservation_time time not null,
        status varchar(30) not null default 'PENDING',
        created_at timestamp(6),
        updated_at timestamp(6),
        primary key (id),
        constraint FK_rest_res_cust foreign key (customer_id) references users(id),
        constraint FK_rest_res_book foreign key (hotel_booking_id) references bookings(id),
        constraint FK_rest_res_cat foreign key (category_id) references restaurant_categories(id),
        constraint FK_rest_res_table foreign key (table_id) references restaurant_tables(id)
    );

    create table menu_categories (
        id bigint generated by default as identity,
        name varchar(100) not null unique,
        primary key (id)
    );

    create table menu_items (
        id bigint generated by default as identity,
        category_id bigint not null,
        name varchar(100) not null,
        description TEXT,
        price numeric(10,2) not null,
        is_active boolean default true,
        primary key (id),
        constraint FK_menu_item_cat foreign key (category_id) references menu_categories(id)
    );

    create table restaurant_bills (
        id uuid not null,
        reservation_id uuid not null unique,
        customer_id uuid not null,
        subtotal numeric(12,2) not null,
        tax numeric(12,2) not null,
        grand_total numeric(12,2) not null,
        payment_method varchar(30),
        payment_status varchar(30) not null default 'PENDING',
        created_at timestamp(6),
        primary key (id),
        constraint FK_rest_bill_res foreign key (reservation_id) references restaurant_reservations(id),
        constraint FK_rest_bill_cust foreign key (customer_id) references users(id)
    );

    create table restaurant_bill_items (
        id bigint generated by default as identity,
        bill_id uuid not null,
        menu_item_id bigint not null,
        quantity integer not null,
        price numeric(10,2) not null,
        primary key (id),
        constraint FK_rest_bill_item_bill foreign key (bill_id) references restaurant_bills(id),
        constraint FK_rest_bill_item_menu foreign key (menu_item_id) references menu_items(id)
    );

    -- Also insert ROLE_CUSTOMER into roles table
    INSERT INTO roles (name, description) VALUES ('ROLE_CUSTOMER', 'Restaurant and Hotel Customer');
